# Greenhouse companies grouped by category
# Edit freely; the loader will lowercase, trim, and deâ€‘duplicate.
# You can also add new categories (keys) anytime.

Major_Tech:
  - figma
  - gitlab
  - robinhood
  - airtable

Fintech:
  - affirm
  - carta
  - checkr
  - earnin 
  - gusto 
  - mercury 

Developer_Tools_and_Infra:
  - buildkite

Cloud_and_Data_Infra:
  - airbyte

AI_and_ML:
  - anthropic

Healthcare_and_Biotech:
  - honehealth
  - springhealth66
  - vivian
  - stellarhealth

Ecommerce_and_Retail:
  - quince
  - mejuri
  - doordashusa
  - aninebing

EdTech:
  - coursera
  - degreed

Climate_and_Sustainability:
  - cc
  - aircompany

Logistics_and_Supply_Chain:
  - weee
  - acommerce
  - bringg

Marketing_and_Advertising:
  - oliverusa
  - oliverusa
  - oliverusa

Sales_and_CRM:
  - 6sense
  - demandbase

Product_and_Analytics:
  - amplitude
  - dovetail

Design_and_Creative:
  - clutch
  - automatticcareers 

Legal_Tech:
  - netdocuments
  - xai

Insurance_Tech:
  - ethoslife 
  - pieinsurance

Construction_Tech:
  - constrafor

Food_and_Agriculture:
  - apeel

Travel_and_Hospitality:
  - agoda

Blockchain_and_Crypto:
  - blockchain
  - fireblocks

Vector_and_Search_Tech:
  - algolia
